package cz.fi.muni.pa165.secretservice.enums;

/**
 * @author tomco
 */
public enum Training {
    CRIMINAL_INVESTIGATOR_TRAINING_PROGRAM, FIREARMS_MARKSMANSHIP,
    PHYSICAL_SITE_OR_EVENT_PROTECTION, EMERGENCY_MEDICAL_TECHNIQUES,
    USE_OF_CONTROL_TACTICS, FINANCIAL_CRIMES_DETECTION
}
